### DISCUSSION TITLE
OVOS Docker skills not available to use

### DISCUSSION THREAD

**Discussion by DreadFog** [OpenVoiceOS/ovos-buildroot#275] [Q&A]
Hi there,

I've been following the tutorial until here: https://openvoiceos.github.io/ovos-docker/getting-started/docker/cli/

Then I tried listing the different skills available to use, only to find a single one available: skill-ovos-boot-finished.openvoiceos

How do I add the other ones? 

FYI, I have all of those containers running:

```
CONTAINER ID   IMAGE                                        COMMAND                  CREATED        STATUS                  PORTS     NAMES
60362f7085ea   smartgic/hivemind-cli:alpha                  "sleep infinity"         10 hours ago   Up 10 hours                       hivemind_cli
65f8e2d91ca2   smartgic/hivemind-listener:alpha             "hivemind-core listen"   10 hours ago   Up 10 hours                       hivemind_listener
c8e7ceb63267   smartgic/ovos-skill-volume:alpha             "ovos-skill-launcher…"   11 hours ago   Up 10 hours                       ovos_skill_volume
02ffcd6cd206   smartgic/ovos-skill-weather:alpha            "ovos-skill-launcher…"   11 hours ago   Up 10 hours                       ovos_skill_weather
498951f7f2f5   smartgic/ovos-skill-duckduckgo:alpha         "ovos-skill-launcher…"   11 hours ago   Up 10 hours                       ovos_skill_duckduckgo
86942bf6442f   smartgic/ovos-skill-fallback-unknown:alpha   "ovos-skill-launcher…"   11 hours ago   Up 10 hours                       ovos_skill_fallback_unknown
5152123c8ac2   smartgic/ovos-skill-alerts:alpha             "ovos-skill-launcher…"   11 hours ago   Up 10 hours                       ovos_skill_alerts
f7fdf79b1259   smartgic/ovos-skill-wikipedia:alpha          "ovos-skill-launcher…"   11 hours ago   Up 10 hours                       ovos_skill_wikipedia
e6622e96a0c0   smartgic/ovos-skill-date-time:alpha          "ovos-skill-launcher…"   11 hours ago   Up 10 hours                       ovos_skill_date_time
73619d4f9b69   smartgic/ovos-skill-ggwave:alpha             "ovos-skill-launcher…"   11 hours ago   Up 10 hours                       ovos_skill_ggwave
baa4b7411321   smartgic/ovos-skill-hello-world:alpha        "ovos-skill-launcher…"   11 hours ago   Up 10 hours                       ovos_skill_hello_world
b6274dc49d59   smartgic/ovos-skill-personal:alpha           "ovos-skill-launcher…"   11 hours ago   Up 10 hours                       ovos_skill_personal
367b1f9c265c   smartgic/ovos-listener-dinkum:alpha          "/bin/bash /usr/loca…"   11 hours ago   Up 10 hours (healthy)             ovos_listener
8392d514325c   smartgic/ovos-audio:alpha                    "/bin/bash /usr/loca…"   11 hours ago   Up 10 hours (healthy)             ovos_audio
a2719930b01c   smartgic/ovos-core:alpha                     "/bin/bash /usr/loca…"   11 hours ago   Up 10 hours (healthy)             ovos_core
2d6ceb525d38   smartgic/ovos-plugin-ggwave:alpha            "/bin/bash -c ovos-g…"   11 hours ago   Up 10 hours                       ovos_plugin_ggwave
215ac3abd013   smartgic/ovos-phal-admin:alpha               "/bin/bash /usr/loca…"   11 hours ago   Up 10 hours (healthy)             ovos_phal_admin
973013feb0d8   smartgic/ovos-phal:alpha                     "/bin/bash /usr/loca…"   11 hours ago   Up 10 hours (healthy)             ovos_phal
f412fbeeba59   smartgic/ovos-cli:alpha                      "sleep infinity"         11 hours ago   Up 10 hours                       ovos_cli
840b3c28b92b   smartgic/ovos-messagebus:alpha               "/bin/bash -c ovos-m…"   11 hours ago   Up 10 hours (healthy)             ovos_messagebus
```

I don't really know how I should tackle troubleshooting. I'll anticipate some questions:

I'm running everything from portainer, with an env file correctly set and a single docker-compose file. I basically copy-pasted the different compose files into a single one. Here it is:
```
---
version: "3.9"

x-podman: &podman
  userns_mode: keep-id
  security_opt:
    - "label=disable"

x-logging: &default-logging
  driver: json-file
  options:
    mode: non-blocking
    max-buffer-size: 4m
    max-size: "200m"
    max-file: "1"

volumes:
  ovos_models:
    name: ovos_models
    driver: local
  ovos_vosk:
    name: ovos_vosk
    driver: local
  ovos_listener_records:
    name: ovos_listener_records
    driver: local
  ovos_tts_cache:
    name: ovos_tts_cache
    driver: local
  ovos_nltk:
    name: ovos_nltk
    driver: local
  ovos_local_state:
    name: ovos_local_state
    driver: local

services:
  ovos_messagebus:
    <<: *podman
    container_name: ovos_messagebus
    hostname: ovos_messagebus
    restart: unless-stopped
    image: docker.io/smartgic/ovos-messagebus:${VERSION}
    logging: *default-logging
    pull_policy: $PULL_POLICY
    environment:
      TZ: $TZ
    network_mode: host
    volumes:
      - ${OVOS_CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft:ro
      - ovos_local_state:/home/${OVOS_USER}/.local/state/mycroft
      - ${TMP_FOLDER}:/tmp/mycroft

  ovos_phal:
    <<: *podman
    container_name: ovos_phal
    hostname: ovos_phal
    restart: unless-stopped
    image: docker.io/smartgic/ovos-phal:${VERSION}
    logging: *default-logging
    pull_policy: $PULL_POLICY
    environment:
      PULSE_SERVER: unix:${XDG_RUNTIME_DIR}/pulse/native
      PULSE_COOKIE: /home/${OVOS_USER}/.config/pulse/cookie
      TZ: $TZ
      XDG_RUNTIME_DIR: $XDG_RUNTIME_DIR
    network_mode: host
    privileged: true
    volumes:
      - ~/.config/pulse/cookie:/home/${OVOS_USER}/.config/pulse/cookie:ro
      - ${OVOS_CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft
      - ${OVOS_CONFIG_PHAL_FOLDER}:/home/${OVOS_USER}/.config/OpenVoiceOS
      - ovos_local_state:/home/${OVOS_USER}/.local/state/mycroft
      - ${TMP_FOLDER}:/tmp/mycroft
      - ${XDG_RUNTIME_DIR}/pipewire-0:${XDG_RUNTIME_DIR}/pipewire-0:ro
      - ${XDG_RUNTIME_DIR}/pulse:${XDG_RUNTIME_DIR}/pulse:ro
    depends_on:
      ovos_messagebus:
        condition: service_started

  ovos_phal_admin:
    <<: *podman
    container_name: ovos_phal_admin
    hostname: ovos_phal_admin
    restart: unless-stopped
    image: docker.io/smartgic/ovos-phal-admin:${VERSION}
    logging: *default-logging
    pull_policy: $PULL_POLICY
    environment:
      TZ: $TZ
    network_mode: host
    privileged: true
    volumes:
      - ${OVOS_CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft
      - ${OVOS_CONFIG_PHAL_FOLDER}:/home/${OVOS_USER}/.config/OpenVoiceOS
      - ovos_local_state:/home/${OVOS_USER}/.local/state/mycroft
      - ${TMP_FOLDER}:/tmp/mycroft
      - /sys:/sys:ro
      - /dev:/dev:ro
    depends_on:
      ovos_messagebus:
        condition: service_started

  ovos_listener:
    <<: *podman
    container_name: ovos_listener
    hostname: ovos_listener
    restart: unless-stopped
    image: docker.io/smartgic/ovos-listener-dinkum:${VERSION}
    logging: *default-logging
    pull_policy: $PULL_POLICY
    environment:
      PULSE_SERVER: unix:${XDG_RUNTIME_DIR}/pulse/native
      PULSE_COOKIE: /home/${OVOS_USER}/.config/pulse/cookie
      TZ: $TZ
      XDG_RUNTIME_DIR: $XDG_RUNTIME_DIR
    network_mode: host
    devices:
      - /dev/snd
    volumes:
      - ~/.config/pulse/cookie:/home/${OVOS_USER}/.config/pulse/cookie:ro
      - ${OVOS_CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft:ro
      - ovos_listener_records:/home/${OVOS_USER}/.local/share/mycroft/listener
      - ovos_local_state:/home/${OVOS_USER}/.local/state/mycroft
      - ovos_models:/home/${OVOS_USER}/.local/share/precise-lite
      - ovos_vosk:/home/${OVOS_USER}/.local/share/vosk
      - ${TMP_FOLDER}:/tmp/mycroft
      - ${XDG_RUNTIME_DIR}/pipewire-0:${XDG_RUNTIME_DIR}/pipewire-0:ro
      - ${XDG_RUNTIME_DIR}/pulse:${XDG_RUNTIME_DIR}/pulse:ro
    depends_on:
      ovos_messagebus:
        condition: service_started
      ovos_phal:
        condition: service_started

  ovos_plugin_ggwave:
    <<: *podman
    container_name: ovos_plugin_ggwave
    hostname: ovos_plugin_ggwave
    restart: unless-stopped
    image: docker.io/smartgic/ovos-plugin-ggwave:${VERSION}
    logging: *default-logging
    pull_policy: $PULL_POLICY
    environment:
      PULSE_SERVER: unix:${XDG_RUNTIME_DIR}/pulse/native
      PULSE_COOKIE: /home/${OVOS_USER}/.config/pulse/cookie
      TZ: $TZ
      XDG_RUNTIME_DIR: $XDG_RUNTIME_DIR
    network_mode: host
    devices:
      - /dev/snd
    volumes:
      - ~/.config/pulse/cookie:/home/${OVOS_USER}/.config/pulse/cookie:ro
      - ${OVOS_CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft:ro
      - ${TMP_FOLDER}:/tmp/mycroft
      - ${XDG_RUNTIME_DIR}/pipewire-0:${XDG_RUNTIME_DIR}/pipewire-0:ro
      - ${XDG_RUNTIME_DIR}/pulse:${XDG_RUNTIME_DIR}/pulse:ro
    depends_on:
      ovos_messagebus:
        condition: service_started
      ovos_phal:
        condition: service_started

  ovos_audio:
    <<: *podman
    container_name: ovos_audio
    hostname: ovos_audio
    restart: unless-stopped
    image: docker.io/smartgic/ovos-audio:${VERSION}
    logging: *default-logging
    pull_policy: $PULL_POLICY
    environment:
      DBUS_SESSION_BUS_ADDRESS: unix:path=${XDG_RUNTIME_DIR}/bus
      PULSE_SERVER: unix:${XDG_RUNTIME_DIR}/pulse/native
      PULSE_COOKIE: /home/${OVOS_USER}/.config/pulse/cookie
      TZ: $TZ
      XDG_RUNTIME_DIR: $XDG_RUNTIME_DIR
    network_mode: host
    devices:
      - /dev/snd
    volumes:
      - ~/.config/pulse/cookie:/home/${OVOS_USER}/.config/pulse/cookie:ro
      - ${OVOS_CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft
      - ovos_local_state:/home/${OVOS_USER}/.local/state/mycroft
      - ovos_tts_cache:/home/${OVOS_USER}/.cache/mycroft
      - ${TMP_FOLDER}:/tmp/mycroft
      - ${XDG_RUNTIME_DIR}/bus:${XDG_RUNTIME_DIR}/bus:ro
      - ${XDG_RUNTIME_DIR}/pipewire-0:${XDG_RUNTIME_DIR}/pipewire-0:ro
      - ${XDG_RUNTIME_DIR}/pulse:${XDG_RUNTIME_DIR}/pulse:ro
    depends_on:
      ovos_messagebus:
        condition: service_started
      ovos_phal:
        condition: service_started

  ovos_core:
    <<: *podman
    container_name: ovos_core
    hostname: ovos_core
    restart: unless-stopped
    image: docker.io/smartgic/ovos-core:${VERSION}
    logging: *default-logging
    pull_policy: $PULL_POLICY
    environment:
      PULSE_SERVER: unix:${XDG_RUNTIME_DIR}/pulse/native
      PULSE_COOKIE: /home/${OVOS_USER}/.config/pulse/cookie
      TZ: $TZ
      XDG_RUNTIME_DIR: $XDG_RUNTIME_DIR
    network_mode: host
    devices:
      - /dev/snd
    volumes:
      - ~/.config/pulse/cookie:/home/${OVOS_USER}/.config/pulse/cookie:ro
      - ${OVOS_CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft
      - ovos_local_state:/home/${OVOS_USER}/.local/state/mycroft
      - ovos_nltk:/home/${OVOS_USER}/nltk_data
      - ${OVOS_SHARE_FOLDER}:/home/${OVOS_USER}/.local/share/mycroft
      - ${TMP_FOLDER}:/tmp/mycroft
      - ${XDG_RUNTIME_DIR}/pipewire-0:${XDG_RUNTIME_DIR}/pipewire-0:ro
      - ${XDG_RUNTIME_DIR}/pulse:${XDG_RUNTIME_DIR}/pulse:ro
    depends_on:
      ovos_messagebus:
        condition: service_started
      ovos_phal:
        condition: service_started

  ovos_cli:
    <<: *podman
    container_name: ovos_cli
    hostname: ovos_cli
    restart: unless-stopped
    image: docker.io/smartgic/ovos-cli:${VERSION}
    logging: *default-logging
    pull_policy: $PULL_POLICY
    environment:
      TZ: $TZ
    network_mode: host
    volumes:
      - ${OVOS_CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft
      - ovos_local_state:/home/${OVOS_USER}/.local/state/mycroft
      - ${TMP_FOLDER}:/tmp/mycroft
    depends_on:
      ovos_messagebus:
        condition: service_started

  ovos_skill_wikipedia:
    <<: *podman
    container_name: ovos_skill_wikipedia
    hostname: ovos_skill_wikipedia
    restart: unless-stopped
    image: docker.io/smartgic/ovos-skill-wikipedia:${VERSION}
    logging: *default-logging
    pull_policy: $PULL_POLICY
    environment:
      TZ: $TZ
    network_mode: host
    volumes:
      - ${OVOS_CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft
      - ovos_nltk:/home/${OVOS_USER}/nltk_data
      - ${TMP_FOLDER}:/tmp/mycroft
    depends_on:
      ovos_core:
        condition: service_started

  ovos_skill_weather:
    <<: *podman
    container_name: ovos_skill_weather
    hostname: ovos_skill_weather
    restart: unless-stopped
    image: docker.io/smartgic/ovos-skill-weather:${VERSION}
    logging: *default-logging
    pull_policy: $PULL_POLICY
    environment:
      TZ: $TZ
    network_mode: host
    volumes:
      - ${OVOS_CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft
      - ${TMP_FOLDER}:/tmp/mycroft
    depends_on:
      ovos_core:
        condition: service_started

  ovos_skill_volume:
    <<: *podman
    container_name: ovos_skill_volume
    hostname: ovos_skill_volume
    restart: unless-stopped
    image: docker.io/smartgic/ovos-skill-volume:${VERSION}
    logging: *default-logging
    pull_policy: $PULL_POLICY
    environment:
      TZ: $TZ
    network_mode: host
    volumes:
      - ${OVOS_CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft
      - ${TMP_FOLDER}:/tmp/mycroft
    depends_on:
      ovos_core:
        condition: service_started

  ovos_skill_date_time:
    <<: *podman
    container_name: ovos_skill_date_time
    hostname: ovos_skill_date_time
    restart: unless-stopped
    image: docker.io/smartgic/ovos-skill-date-time:${VERSION}
    logging: *default-logging
    pull_policy: $PULL_POLICY
    environment:
      TZ: $TZ
    network_mode: host
    volumes:
      - ${OVOS_CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft
      - ${TMP_FOLDER}:/tmp/mycroft
    depends_on:
      ovos_core:
        condition: service_started

  ovos_skill_personal:
    <<: *podman
    container_name: ovos_skill_personal
    hostname: ovos_skill_personal
    restart: unless-stopped
    image: docker.io/smartgic/ovos-skill-personal:${VERSION}
    logging: *default-logging
    pull_policy: $PULL_POLICY
    environment:
      TZ: $TZ
    network_mode: host
    volumes:
      - ${OVOS_CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft
      - ${TMP_FOLDER}:/tmp/mycroft
    depends_on:
      ovos_core:
        condition: service_started

  ovos_skill_fallback_unknown:
    <<: *podman
    container_name: ovos_skill_fallback_unknown
    hostname: ovos_skill_fallback_unknown
    restart: unless-stopped
    image: docker.io/smartgic/ovos-skill-fallback-unknown:${VERSION}
    logging: *default-logging
    pull_policy: $PULL_POLICY
    environment:
      TZ: $TZ
    network_mode: host
    volumes:
      - ${OVOS_CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft
      - ${TMP_FOLDER}:/tmp/mycroft
    depends_on:
      ovos_core:
        condition: service_started

  ovos_skill_hello_world:
    <<: *podman
    container_name: ovos_skill_hello_world
    hostname: ovos_skill_hello_world
    restart: unless-stopped
    image: docker.io/smartgic/ovos-skill-hello-world:${VERSION}
    logging: *default-logging
    pull_policy: $PULL_POLICY
    environment:
      TZ: $TZ
    network_mode: host
    volumes:
      - ${OVOS_CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft
      - ${TMP_FOLDER}:/tmp/mycroft
    depends_on:
      ovos_core:
        condition: service_started

  ovos_skill_alerts:
    <<: *podman
    container_name: ovos_skill_alerts
    hostname: ovos_skill_alerts
    restart: unless-stopped
    image: docker.io/smartgic/ovos-skill-alerts:${VERSION}
    logging: *default-logging
    pull_policy: $PULL_POLICY
    environment:
      TZ: $TZ
    network_mode: host
    volumes:
      - ${OVOS_CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft
      - ${TMP_FOLDER}:/tmp/mycroft
    depends_on:
      ovos_core:
        condition: service_started

  ovos_skill_ggwave:
    <<: *podman
    container_name: ovos_skill_ggwave
    hostname: ovos_skill_ggwave
    restart: unless-stopped
    image: docker.io/smartgic/ovos-skill-ggwave:${VERSION}
    logging: *default-logging
    pull_policy: $PULL_POLICY
    environment:
      TZ: $TZ
    network_mode: host
    volumes:
      - ${OVOS_CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft
      - ${TMP_FOLDER}:/tmp/mycroft
    depends_on:
      ovos_core:
        condition: service_started

  ovos_skill_duckduckgo:
    <<: *podman
    container_name: ovos_skill_duckduckgo
    hostname: ovos_skill_duckduckgo
    restart: unless-stopped
    image: docker.io/smartgic/ovos-skill-duckduckgo:${VERSION}
    logging: *default-logging
    pull_policy: $PULL_POLICY
    environment:
      TZ: $TZ
    network_mode: host
    volumes:
      - ${OVOS_CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft
      - ${TMP_FOLDER}:/tmp/mycroft
    depends_on:
      ovos_core:
        condition: service_started

  hivemind_listener:
    <<: *podman
    container_name: hivemind_listener
    hostname: hivemind_listener
    restart: unless-stopped
    image: docker.io/smartgic/hivemind-listener:${VERSION}
    logging: *default-logging
    pull_policy: $PULL_POLICY
    tty: true
    environment:
      TZ: $TZ
    network_mode: host
    volumes:
      - ${HIVEMIND_CONFIG_FOLDER}:/home/${HIVEMIND_USER}/.config/hivemind:z
      - ${HIVEMIND_SHARE_FOLDER}:/home/${HIVEMIND_USER}/.local/share/hivemind:z
    depends_on:
      ovos_core:
        condition: service_started

  hivemind_cli:
    <<: *podman
    container_name: hivemind_cli
    hostname: hivemind_cli
    restart: unless-stopped
    image: docker.io/smartgic/hivemind-cli:${VERSION}
    logging: *default-logging
    pull_policy: $PULL_POLICY
    tty: true
    environment:
      TZ: $TZ
    network_mode: host
    volumes:
      - ${HIVEMIND_CONFIG_FOLDER}:/home/${HIVEMIND_USER}/.config/hivemind:z
      - ${HIVEMIND_SHARE_FOLDER}:/home/${HIVEMIND_USER}/.local/share/hivemind:z
    depends_on:
      hivemind_listener:
        condition: service_started
```

Here are my env variables:

```
DISPLAY=:0
HIVEMIND_CONFIG_FOLDER=/home/dreadfog/SSD/services/openvoice_os/hivemind/config
HIVEMIND_CONFIG_PHAL_FOLDER=/home/dreadfog/SSD/services/openvoice_os/hivemind/config/phal
HIVEMIND_SHARE_FOLDER=/home/dreadfog/SSD/services/openvoice_os/hivemind/share
HIVEMIND_USER=hivemind
INPUT_GID=102
OVOS_CONFIG_FOLDER=/home/dreadfog/SSD/services/openvoice_os/ovos/config
OVOS_CONFIG_PHAL_FOLDER=/home/dreadfog/SSD/services/openvoice_os/ovos/config/phal
OVOS_SHARE_FOLDER=/home/dreadfog/SSD/services/openvoice_os/ovos/share
OVOS_USER=ovos
PULL_POLICY=always
QT_QPA_EGLFS_INTEGRATION=eglfs_kms
QT_QPA_EGLFS_KMS_CONFIG=/home/$OVOS_USER/.config/mycroft/ovos-eglfs.json
QT_QPA_PLATFORM=eglfs
RENDER_GID=106
TMP_FOLDER=/home/dreadfog/SSD/services/openvoice_os/ovos/tmp
TZ=Europe/Paris
VERSION=alpha
VIDEO_GID=44
WAYLAND_DISPLAY=wayland-0
XDG_RUNTIME_DIR=/run/user/1000
```

where dreadfog is the user on the host machine

Here are the skills that are (supposedly) installed:

```
> pwd
/home/dreadfog/SSD/services/openvoice_os/ovos/config/skills
> ll
total 52K
4.0K drwxr-xr-x 13 dreadfog dreadfog 4.0K Sep  2 23:48 ./
4.0K drwxr-xr-x  5 dreadfog dreadfog 4.0K Sep  3 00:32 ../
4.0K drwxr-xr-x  2 dreadfog dreadfog 4.0K Sep  2 23:48 ovos-skill-alerts.openvoiceos/
4.0K drwxr-xr-x  2 dreadfog dreadfog 4.0K Sep  2 23:48 ovos-skill-ggwave.openvoiceos/
4.0K drwxr-xr-x  2 dreadfog dreadfog 4.0K Sep  2 23:48 ovos-skill-personal.OpenVoiceOS/
4.0K drwxr-xr-x  2 dreadfog dreadfog 4.0K Sep  2 23:42 skill-ovos-boot-finished.openvoiceos/
4.0K drwxr-xr-x  2 dreadfog dreadfog 4.0K Sep  2 23:48 skill-ovos-date-time.openvoiceos/
4.0K drwxr-xr-x  2 dreadfog dreadfog 4.0K Sep  2 23:48 skill-ovos-ddg.openvoiceos/
4.0K drwxr-xr-x  2 dreadfog dreadfog 4.0K Sep  2 23:48 skill-ovos-fallback-unknown.openvoiceos/
4.0K drwxr-xr-x  2 dreadfog dreadfog 4.0K Sep  2 23:48 skill-ovos-hello-world.openvoiceos/
4.0K drwxr-xr-x  2 dreadfog dreadfog 4.0K Sep  2 23:48 skill-ovos-volume.openvoiceos/
4.0K drwxr-xr-x  2 dreadfog dreadfog 4.0K Sep  2 23:48 skill-ovos-weather.openvoiceos/
4.0K drwxr-xr-x  2 dreadfog dreadfog 4.0K Sep  2 23:48 skill-ovos-wikipedia.openvoiceos/
```

Here is the "skills" section of the ` docker exec --interactive --tty ovos_cli ovos-config show` command

```
│ skills                                                       │                                                                                                                                                                  │
│     directory                                                │ skills                                                                                                                                                           │
│     upload_skill_manifest                                    │ False                                                                                                                                                            │
│     sync2way                                                 │ True                                                                                                                                                             │
│     autogen_meta                                             │ False                                                                                                                                                            │
│     blacklisted_skills                                       │ ['skill-ovos-stop.openvoiceos']                                                                                                                                  │
│     fallbacks                                                │                                                                                                                                                                  │
│         fallback_priorities                                  │                                                                                                                                                                  │
│         fallback_mode                                        │ accept_all                                                                                                                                                       │
│         fallback_whitelist                                   │ []                                                                                                                                                               │
│         fallback_blacklist                                   │ []                                                                                                                                                               │
│     converse                                                 │                                                                                                                                                                  │
│         timeout                                              │ 300                                                                                                                                                              │
│         skill_timeouts                                       │                                                                                                                                                                  │
│         converse_mode                                        │ accept_all                                                                                                                                                       │
│         converse_whitelist                                   │ []                                                                                                                                                               │
│         converse_blacklist                                   │ []                                                                                                                                                               │
│         converse_activation                                  │ accept_all                                                                                                                                                       │
│         max_activations                                      │ -1                                                                                                                                                               │
│         skill_activations                                    │                                                                                                                                                                  │
│         cross_activation                                     │ True                                                                                                                                                             │
│         cross_deactivation                                   │ True                                                                                                                                                             │
│         converse_priorities   
```
