### DISCUSSION TITLE
Install satellite

### DISCUSSION THREAD

**Discussion by corazon008** [OpenVoiceOS/ovos-buildroot#286] [Q&A]
Hello,
I installed the `satellite` profile on my rpi4 (the ovos config work fine but I want to improve performance) but after the installation :
- no voice telling me he his ready
- no answer to 'Hey mycroft"

Rpi4 with `satellite` profile (clean installation from raspiOS lite): 
![image](https://github.com/user-attachments/assets/3b770983-f1ac-47aa-8009-1ef8d4b56510)
![image](https://github.com/user-attachments/assets/c4d9993e-181b-4a29-a50f-b973ee88a174)
![image](https://github.com/user-attachments/assets/64381586-ae08-4133-be4f-554f7e680961)
```
---
uninstall: false
method: virtualenv
channel: development
profile: satellite
hivemind:
  host: 192.168.1.75
  port: 5678
  key: edf0af5131dc2000cda6954efca60585
  password: ovos
features:
  skills: false
  extra_skills: false
  gui: false
rapsberry_pi_tuning: true
share_telemetry: true
```
![image](https://github.com/user-attachments/assets/65f25237-06e1-45c2-9adc-95e9876fb5ac)

Server with `server` profile  `192.168.1.75` : 
![image](https://github.com/user-attachments/assets/38c9dbdf-8505-4f1e-9f80-cfa5ae23457d)
![image](https://github.com/user-attachments/assets/49d637b0-590a-4775-8251-68d18bad9a10)

I don't know what is normal and what is not but I think I sould at least be able to speak to it 😆
